### ISSUE TITLE
Update to Present Tense

### ISSUE THREAD

**Issue by MawsayB** [rickerje/liftoff-assignments#1]
@rickerje 👍 This is really strong!  To get this ready for your project repo (b/c you'll use this as the README.md ([example](https://github.com/MawsayB/GymRat/blob/master/README.md)), update:

- "Outliner **will be** a Web-based app" to present tense "Outliner **is** a Web-based app".
- Outliner **benefits** both groups. **For the** plotter **it is** an easy, intuitive way to create...
- there are a few more spots in your final Overview paragraph and Features

Because you're still building this all out, updating the verb tense might not make complete sense right now, but it will be helpful when you're showing a potential employer.

**Comment by rickerje** [comment]
@MawsayB 
Forgot to close this out when I did it--doing now to get into practice) Updated to present tense throughout!
